require:
  - rubocop-rails

Rails:
  Enabled: true

Rails/UnknownEnv:
  Environments:
    - production
    - development
    - test
    - staging

Style/SymbolArray:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/EmptyMethod:
  EnforcedStyle: expanded
Style/FrozenStringLiteralComment:
  Enabled: false
Style/RegexpLiteral:
  EnforcedStyle: slashes
  AllowInnerSlashes: true
Style/GlobalVars:
  AllowedVariables:
    - $redis
    - $houston
Style/WordArray:
  EnforcedStyle: brackets

Layout/SpaceAroundMethodCallOperator:
 Enabled: False
Layout/SpaceInLambdaLiteral:
  Enabled: true
  EnforcedStyle: require_space
Layout/LineLength:
  Exclude:
    - config/routes.rb
    - config/initializers/**/*.rb

Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - '**/*.rake'
    - config/routes.rb
    - test/**/*_test.rb

Lint/RaiseException:
  Enabled: false

Lint/StructNewOverride:
  Enabled: false

Style/ExponentialNotation:
  Enabled: false
Style/HashEachMethods:
  Enabled: false
Style/HashTransformKeys:
  Enabled: false
Style/HashTransformValues:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.6.5
  Exclude:
    - node_modules/**/*
    - script/**/*
    - bin/**/*
    - db/**/*
    - app/views/**/*.slim
