default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: makerble_app_development

test:
  <<: *default
  database: makerble_app_test

production:
  <<: *default
  database: makerble_app_production
  username: makerble_app
  password: <%= ENV['RSS_READER_DATABASE_PASSWORD'] %>
